/**
 * Generated by `supabase gen types typescript` (via the Supabase MCP) against
 * the live schema, then extended at the bottom with hand-maintained enum
 * unions, jsonb sub-shapes and convenience aliases.
 *
 * REGENERATE THIS after any migration, or queries silently collapse to `never`.
 * Keep the "Supplementary" section at the bottom.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      addresses: {
        Row: {
          city: string
          customer_id: string | null
          full_address: string
          id: string
          is_default: boolean | null
          label: string | null
        }
        Insert: {
          city: string
          customer_id?: string | null
          full_address: string
          id?: string
          is_default?: boolean | null
          label?: string | null
        }
        Update: {
          city?: string
          customer_id?: string | null
          full_address?: string
          id?: string
          is_default?: boolean | null
          label?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "addresses_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_users: {
        Row: {
          created_at: string | null
          email: string
          full_name: string
          id: string
          is_active: boolean | null
          role: string
        }
        Insert: {
          created_at?: string | null
          email: string
          full_name: string
          id: string
          is_active?: boolean | null
          role?: string
        }
        Update: {
          created_at?: string | null
          email?: string
          full_name?: string
          id?: string
          is_active?: boolean | null
          role?: string
        }
        Relationships: []
      }
      cities: {
        Row: {
          id: string
          is_active: boolean | null
          name: string
        }
        Insert: {
          id?: string
          is_active?: boolean | null
          name: string
        }
        Update: {
          id?: string
          is_active?: boolean | null
          name?: string
        }
        Relationships: []
      }
      customers: {
        Row: {
          auth_user_id: string | null
          city: string | null
          created_at: string | null
          email: string | null
          id: string
          name: string
          phone: string
        }
        Insert: {
          auth_user_id?: string | null
          city?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          name: string
          phone: string
        }
        Update: {
          auth_user_id?: string | null
          city?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          name?: string
          phone?: string
        }
        Relationships: []
      }
      invoices: {
        Row: {
          created_at: string | null
          customer_id: string | null
          discount: number | null
          due_date: string | null
          id: string
          invoice_number: string
          issue_date: string | null
          order_id: string | null
          paid_at: string | null
          payment_method: string | null
          pdf_url: string | null
          status: string
          subtotal: number
          tax: number | null
          total: number
        }
        Insert: {
          created_at?: string | null
          customer_id?: string | null
          discount?: number | null
          due_date?: string | null
          id?: string
          invoice_number?: string // trigger-generated (gen_invoice_number)
          issue_date?: string | null
          order_id?: string | null
          paid_at?: string | null
          payment_method?: string | null
          pdf_url?: string | null
          status?: string
          subtotal: number
          tax?: number | null
          total: number
        }
        Update: {
          created_at?: string | null
          customer_id?: string | null
          discount?: number | null
          due_date?: string | null
          id?: string
          invoice_number?: string
          issue_date?: string | null
          order_id?: string | null
          paid_at?: string | null
          payment_method?: string | null
          pdf_url?: string | null
          status?: string
          subtotal?: number
          tax?: number | null
          total?: number
        }
        Relationships: [
          {
            foreignKeyName: "invoices_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          id: string
          line_total: number
          order_id: string | null
          qty: number
          service_id: string | null
          service_name: string
          unit_price: number
        }
        Insert: {
          id?: string
          line_total: number
          order_id?: string | null
          qty?: number
          service_id?: string | null
          service_name: string
          unit_price: number
        }
        Update: {
          id?: string
          line_total?: number
          order_id?: string | null
          qty?: number
          service_id?: string | null
          service_name?: string
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          address: string
          assigned_vendor_id: string | null
          city: string
          created_at: string | null
          customer_id: string | null
          discount: number | null
          id: string
          notes: string | null
          order_number: string
          payment_method: string | null
          payment_status: string | null
          scheduled_date: string | null
          scheduled_slot: string | null
          source: string | null
          status: string
          subtotal: number
          tax: number | null
          total: number
          updated_at: string | null
        }
        Insert: {
          address: string
          assigned_vendor_id?: string | null
          city: string
          created_at?: string | null
          customer_id?: string | null
          discount?: number | null
          id?: string
          notes?: string | null
          order_number?: string // trigger-generated (gen_order_number)
          payment_method?: string | null
          payment_status?: string | null
          scheduled_date?: string | null
          scheduled_slot?: string | null
          source?: string | null
          status?: string
          subtotal: number
          tax?: number | null
          total: number
          updated_at?: string | null
        }
        Update: {
          address?: string
          assigned_vendor_id?: string | null
          city?: string
          created_at?: string | null
          customer_id?: string | null
          discount?: number | null
          id?: string
          notes?: string | null
          order_number?: string
          payment_method?: string | null
          payment_status?: string | null
          scheduled_date?: string | null
          scheduled_slot?: string | null
          source?: string | null
          status?: string
          subtotal?: number
          tax?: number | null
          total?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "orders_assigned_vendor_id_fkey"
            columns: ["assigned_vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      price_history: {
        Row: {
          changed_at: string | null
          changed_by: string | null
          id: string
          new_price: number | null
          old_price: number | null
          service_id: string | null
        }
        Insert: {
          changed_at?: string | null
          changed_by?: string | null
          id?: string
          new_price?: number | null
          old_price?: number | null
          service_id?: string | null
        }
        Update: {
          changed_at?: string | null
          changed_by?: string | null
          id?: string
          new_price?: number | null
          old_price?: number | null
          service_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "price_history_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "admin_users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "price_history_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      reviews: {
        Row: {
          comment: string | null
          created_at: string | null
          customer_id: string | null
          id: string
          order_id: string | null
          rating: number
          service_id: string | null
        }
        Insert: {
          comment?: string | null
          created_at?: string | null
          customer_id?: string | null
          id?: string
          order_id?: string | null
          rating: number
          service_id?: string | null
        }
        Update: {
          comment?: string | null
          created_at?: string | null
          customer_id?: string | null
          id?: string
          order_id?: string | null
          rating?: number
          service_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "reviews_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      service_categories: {
        Row: {
          icon: string | null
          id: string
          name: string
          slug: string
          sort_order: number | null
        }
        Insert: {
          icon?: string | null
          id?: string
          name: string
          slug: string
          sort_order?: number | null
        }
        Update: {
          icon?: string | null
          id?: string
          name?: string
          slug?: string
          sort_order?: number | null
        }
        Relationships: []
      }
      services: {
        Row: {
          bookings_count: string | null
          category_id: string | null
          created_at: string | null
          description: string | null
          display_price_label: string | null
          duration: string | null
          faqs: Json | null
          gallery_imgs: Json | null
          hero_img: string | null
          how_it_works: Json | null
          id: string
          is_active: boolean | null
          name: string
          not_included: Json | null
          price: number
          price_unit: string
          rating: number | null
          related_service_ids: string[] | null
          reviews_count: number | null
          slug: string
          tagline: string | null
          updated_at: string | null
          what_we_clean: Json | null
          whats_included: Json | null
        }
        Insert: {
          bookings_count?: string | null
          category_id?: string | null
          created_at?: string | null
          description?: string | null
          display_price_label?: string | null
          duration?: string | null
          faqs?: Json | null
          gallery_imgs?: Json | null
          hero_img?: string | null
          how_it_works?: Json | null
          id?: string
          is_active?: boolean | null
          name: string
          not_included?: Json | null
          price: number
          price_unit?: string
          rating?: number | null
          related_service_ids?: string[] | null
          reviews_count?: number | null
          slug: string
          tagline?: string | null
          updated_at?: string | null
          what_we_clean?: Json | null
          whats_included?: Json | null
        }
        Update: {
          bookings_count?: string | null
          category_id?: string | null
          created_at?: string | null
          description?: string | null
          display_price_label?: string | null
          duration?: string | null
          faqs?: Json | null
          gallery_imgs?: Json | null
          hero_img?: string | null
          how_it_works?: Json | null
          id?: string
          is_active?: boolean | null
          name?: string
          not_included?: Json | null
          price?: number
          price_unit?: string
          rating?: number | null
          related_service_ids?: string[] | null
          reviews_count?: number | null
          slug?: string
          tagline?: string | null
          updated_at?: string | null
          what_we_clean?: Json | null
          whats_included?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "services_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "service_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_documents: {
        Row: {
          doc_type: string
          id: string
          review_note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: string
          storage_path: string
          uploaded_at: string | null
          vendor_id: string
        }
        Insert: {
          doc_type: string
          id?: string
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          storage_path: string
          uploaded_at?: string | null
          vendor_id: string
        }
        Update: {
          doc_type?: string
          id?: string
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          storage_path?: string
          uploaded_at?: string | null
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendor_documents_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "admin_users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_documents_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      vendors: {
        Row: {
          application_note: string | null
          auth_user_id: string | null
          city: string | null
          commission_rate: number | null
          created_at: string | null
          documents: Json | null
          email: string | null
          id: string
          name: string
          onboarded_at: string | null
          onboarding_step: string
          phone: string
          rating: number | null
          rejection_reason: string | null
          services_offered: string[] | null
          status: string
          submitted_at: string | null
        }
        Insert: {
          application_note?: string | null
          auth_user_id?: string | null
          city?: string | null
          commission_rate?: number | null
          created_at?: string | null
          documents?: Json | null
          email?: string | null
          id?: string
          name: string
          onboarded_at?: string | null
          onboarding_step?: string
          phone: string
          rating?: number | null
          rejection_reason?: string | null
          services_offered?: string[] | null
          status?: string
          submitted_at?: string | null
        }
        Update: {
          application_note?: string | null
          auth_user_id?: string | null
          city?: string | null
          commission_rate?: number | null
          created_at?: string | null
          documents?: Json | null
          email?: string | null
          id?: string
          name?: string
          onboarded_at?: string | null
          onboarding_step?: string
          phone?: string
          rating?: number | null
          rejection_reason?: string | null
          services_offered?: string[] | null
          status?: string
          submitted_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      cancel_booking: { Args: { p_order_id: string }; Returns: undefined }
      claim_vendor: {
        Args: {
          p_city: string
          p_email: string
          p_name: string
          p_phone: string
        }
        Returns: string
      }
      create_booking: {
        Args: {
          p_address: string
          p_city: string
          p_email: string
          p_items: Json
          p_name: string
          p_notes?: string
          p_phone: string
          p_scheduled_date: string
          p_slot?: string
        }
        Returns: Json
      }
      current_customer_id: { Args: never; Returns: string }
      current_vendor_id: { Args: never; Returns: string }
      is_admin: { Args: never; Returns: boolean }
      is_super_admin: { Args: never; Returns: boolean }
      my_jobs: {
        Args: never
        Returns: {
          address: string
          city: string
          created_at: string
          customer_name: string
          customer_phone: string
          id: string
          items: Json
          notes: string
          order_number: string
          payment_method: string
          payment_status: string
          scheduled_date: string
          scheduled_slot: string
          status: string
          total: number
          updated_at: string
        }[]
      }
      reschedule_booking: {
        Args: { p_date: string; p_order_id: string; p_slot?: string }
        Returns: undefined
      }
      submit_review: {
        Args: {
          p_comment?: string
          p_order_id: string
          p_rating: number
          p_service_id: string
        }
        Returns: undefined
      }
      submit_vendor_application: {
        Args: {
          p_city: string
          p_email: string
          p_name: string
          p_note?: string
          p_phone: string
        }
        Returns: Json
      }
      submit_vendor_for_review: { Args: never; Returns: undefined }
      update_my_job_status: {
        Args: {
          p_cash_collected?: boolean
          p_order_id: string
          p_status: string
        }
        Returns: undefined
      }
      upsert_my_vendor_profile: {
        Args: {
          p_city: string
          p_email: string
          p_name: string
          p_note?: string
          p_services: string[]
        }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

// ─── Supplementary (hand-maintained) ─────────────────────────────────────────
// CHECK-constraint columns type as plain `string` in generated types; these
// unions give us stronger typing where we opt in.

export type AdminRole = 'super_admin' | 'admin' | 'staff'
export type PriceUnit = 'fixed' | 'per_sqft' | 'per_panel' | 'per_seat'
export type OrderStatus =
  | 'pending'
  | 'confirmed'
  | 'vendor_assigned'
  | 'in_progress'
  | 'completed'
  | 'cancelled'
export type PaymentStatus = 'unpaid' | 'paid' | 'refunded' | 'partial'
export type VendorStatus = 'pending' | 'approved' | 'active' | 'suspended' | 'rejected'
export type InvoiceStatus = 'draft' | 'sent' | 'paid' | 'overdue' | 'void'
export type OrderSource = 'website' | 'crm' | 'phone'

// jsonb sub-shapes (columns are `Json` in generated types)
export interface HowItWorksStep {
  step: number
  title: string
  desc: string
}
export interface Faq {
  q: string
  a: string
}
export interface VendorDocument {
  type: string
  url: string
  verified: boolean
}

// Convenience row aliases
export type AdminUser = Tables<'admin_users'>
export type ServiceCategory = Tables<'service_categories'>
export type City = Tables<'cities'>
export type Service = Tables<'services'>
export type PriceHistory = Tables<'price_history'>
export type Customer = Tables<'customers'>
export type Address = Tables<'addresses'>
export type Order = Tables<'orders'>
export type OrderItem = Tables<'order_items'>
export type Vendor = Tables<'vendors'>
export type Invoice = Tables<'invoices'>
export type Review = Tables<'reviews'>

// KYC (vendor_documents + vendors.onboarding_step) — added with migrations 0008–0011
export type OnboardingStep = 'profile' | 'documents' | 'review' | 'done'
export type KycDocType = 'aadhaar' | 'pan' | 'address_proof' | 'bank_proof' | 'police_verification' | 'photo'
export type KycDocStatus = 'pending' | 'verified' | 'rejected'
export type VendorKycDocument = Tables<'vendor_documents'>
export const KYC_REQUIRED_DOCS: KycDocType[] = ['aadhaar', 'pan', 'address_proof', 'bank_proof']
export const KYC_DOC_LABELS: Record<KycDocType, string> = {
  aadhaar: 'Aadhaar card',
  pan: 'PAN card',
  address_proof: 'Address proof',
  bank_proof: 'Bank proof',
  police_verification: 'Police verification',
  photo: 'Passport photo',
}
